getTopicsApi:
  path:       /api/v1/get-topics
  controller: App\Api\StarWarsController::getTopicList
  methods:    POST

getList:
  path:       /api/v1/get-list/{topic}
  controller: App\Api\StarWarsController::getList
  methods:    POST
  defaults:  { topic: null }

index:
  path:       /
  controller: App\Controller\IndexController::index
  methods:    GET
